# Токен пользователя
# Можно поучить тут 👉 https://vkhost.github.io
USER_TOKEN: ABOBA

# Токен и ID группы. Получаем в настройках
BOT_TOKEN: ABOBA
GROUP_ID: 123

# Команда на запуск бота
TRIGGER: /старт

#### Тексты на кнопках ####
BUTTON_HEADER: vto.pe
BUTTON_1: 💩 Govno 💩
BUTTON_2: 🍑 Jopa 🍑
BUTTON_3: 🐑 Barebuh 🐑
BUTTON_4: 👉 Suka 👌
BUTTON_FOOTER: vkbot.ru

#### Настройки задержек и прочего ####

# Длина каждого отдельного сообщения
MSG_LENGTH: 2000

# Время до следующей отправки сообщения, если это отправлено успешно (в миллисекундах)
SUCCESS_TIMEOUT: 1000

# Время до следующей отправки сообщения, если при отправке произошла ошибка (в миллисекундах)
ERROR_TIMEOUT: 10000

# Общее кол-во сообщений на одну беседу
MESSAGES_COUNT: 100

# Кол-во вариаций сообщения
UNIQUE_MESSAGES: 8

# Домен владельца группы, которому будут приходить оповещения. 
OWNER: durov